# Generated by Django 4.2.2 on 2023-07-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('Description', models.TextField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='products/')),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
